- name: Install Apache
  apt:
    pkg:
    - apache2
    - apache2-dev
    - libapache2-mpm-itk
  become: yes

- name: Load modules via symlink
  file:
    src: /etc/apache2/mods-available/{{ item }}.load
    dest: /etc/apache2/mods-enabled/{{ item }}.load
    owner: root
    group: root
    state: link
  with_items:
    - socache_shmcb
    - ssl
    - headers
    - proxy
    - proxy_http

- name: Configure modules via symlink
  file:
    src: /etc/apache2/mods-available/{{ item }}.conf
    dest: /etc/apache2/mods-enabled/{{ item }}.conf
    owner: root
    group: root
    state: link
  with_items:
    - ssl
    - proxy
