- name: Install the Dead Snakes Python repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  become: yes

- name: Install a list of packages
  apt:
    pkg:
    - python3.8
    - python3.8-dev
    - python3.8-venv
  become: yes
