- name: Install Python 3.8 with development headers and venv support.
  apt:
    pkg:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python3
    - python3-dev
    - python3-pip
    - python3-venv
  become: yes
