---
- name: Create Apache website conf files.
  template:
    src: "apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
  with_items: "{{ websites }}"

- name: Activate websites with symlinks.
  file:
    src: "/etc/apache2/sites-available/{{ item.server_name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.server_name }}.conf"
    owner: root
    group: root
    state: link
  with_items: "{{ websites }}"

- name: Create Green Unicorn configs for each site
  template:
    src: "gunicorn_config.py.j2"
    dest: "{{ item.1.django_root|default(DJANGO_ROOT) }}/gunicorn_{{ item.1.project|replace('-', '_') }}.py"
    owner: "{{ USER }}"
    group: "{{ GROUP }}"
  loop: "{{ websites|subelements('sites') }}"

- name: Create systemd service files for each site
  template:
    src: "gunicorn_systemd_service.j2"
    dest: "/etc/systemd/system/gunicorn_{{ item.1.project|replace('-', '_') }}.service"
  loop: "{{ websites|subelements('sites') }}"

- name: Start site services and enable at boot
  systemd:
    name: "gunicorn_{{ item.1.project|replace('-', '_') }}.service"
    state: started
    enabled: yes
  loop: "{{ websites|subelements('sites') }}"
  
- name: (re)start httpd service
  service:
    name: apache2
    state: restarted
