---
- name: Create Apache website conf files.
  template:
    src: "apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ item.name }}.conf"
  with_items: "{{ websites }}"

- name: Activate websites with symlinks.
  file:
    src: "/etc/apache2/sites-available/{{ item.name }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ item.name }}.conf"
    owner: root
    group: root
    state: link
  with_items: "{{ websites }}"

- name: Create Green Unicorn configs for each site
  template:
    src: "gunicorn_config.py.j2"
    dest: "{{ item.0.django_root|default(DJANGO_ROOT) }}/gunicorn_config_{{ item.1.project|replace("-", "_") }}.py"
  loop: "{{ websites|subelements('sites') }}"

- name: Create Ubuntu service files
  debug:
    msg: "||| {{ item.0 }} *** {{ item.1 }} |||"
  loop: "{{ websites|subelements('sites') }}"

- name: (re)start httpd service
  service:
    name: apache2
    state: restarted
