- name: Install prerequisite packages required by Python packages.
  apt:
    pkg:
    - libcairo2
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libgdk-pixbuf2.0-0
    - libffi-dev
    - shared-mime-info
  become: yes
