- name: Start by denying all ports
  ufw:
    state: enabled
    policy: deny

- name: Allow SSH on port 22
  ufw:
    rule: allow
    name: OpenSSH

- name: Allow all access to tcp port 80, http
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow all access to tcp port 443, https
  ufw:
    rule: allow
    port: '443'
    proto: tcp
