---
- import_playbook: web-common.yml host_group=web_py
- name: Additional tasks to be performed on Python / Django servers
  hosts: web_py
  become: yes
  vars:
    # DEFAULTS for the template, if not overridden in `sites`
    "USER": "web_deploy"
    "GROUP": "www-data"
    "DJANGO_ROOT": "/var/django/sites"
    "STATIC": true
    # Logging level for Apache httpd; must be one of: emerg/alert/crit/error/warn/notice/info/debug/trace1/.../trace8
    "LOG_LEVEL": "error"

    # Websites / domains for these servers to host
    "websites": [
        {
            "name": "hockey",
            "server_name": "hockey.io",
            "server_aliases": [
                "www.hockey.io",
            ],
            "log_level": "warn",
            "sites": [
                {
                    "path": "/philadelphia-flyers",
                    "project": "hockey-philadelphia-flyers",
                },
                {
                    "path": "/",
                    "project": "hockey-main",
                }
            ]
        },
        {
            "name": "football",
            "server_name": "football.io",
            "server_aliases": [
                "www.football.io",
                "soccer.io",
                "www.soccer.io",
            ],
            "sites": [
                {
                    "path": "/world-cup",
                    "project": "football-world-cup",
                },
                {
                    "path": "/",
                    "project": "football-main",
                }
            ]
        },
    ]
  roles:
    - { role: "postgresql-12", tags: ["python"] }
    - { role: "python-3.8", tags: ["python"] }
    - { role: "python-3.8-pdf-prereqs", tags: ["python"] }
    - { role: "apache", tags: ["apache"] }
    - { role: "apache-django-deploy", tags: ["apache", "django"] }
    - { role: "apache-gunicorn-config", tags: ["apache", "gunicorn", "django"] }
