---
- import_playbook: web-common.yml host_group=web_py
- name: Additional tasks to be performed on Python / Django servers
  hosts: web_py
  become: yes
  vars:
    # DEFAULTS for the template, if not overridden in `sites`
    "USER": "web_deploy"
    "GROUP": "www-data"
    "DJANGO_ROOT": "/var/django/sites"
    "STATIC": true

    # Websites / domains for these servers to host
    "websites": [
        {
            "name": "yourserver",
            "server_name": "yourserver.org",
            "server_aliases": [
                "www.yourserver.org"
            ],
            "sites": [
                {
                    "path": "/",
                    "project": "yourserver",
                }
            ]
        },
    ]
  roles:
    - { role: "python3.8", tags: ["python"] }
    - { role: "apache", tags: ["apache"] }
    - { role: "apache-django-deploy", tags: ["apache"] }
